version: '3.8'

networks:
  inswitch_network:
    name: inswitch_network

services:
  flaskappi:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    networks: 
      - inswitch_network
    command: sleep infinity

  graphdb:
    container_name: graphdb
    image: ontotext/graphdb:10.6.4
    ports:
      - 7200:7200  # Port
    networks: 
      - inswitch_network
    volumes:
      - graphdb-data:/opt/graphdb/home
  
volumes:
  graphdb-data: